name: install-and-cache ruby tools
description: 'GitHub Action to install and cache Ruby tools'
author: 'Office TECOLI, LLC'
branding: 
  color: orange
  icon:  type

inputs:
  tools:    { required: false, type: string }
  cache:    { required: false, type: string, default: yes }
  key:      { required: false, type: string }
  document: { required: false, type: string, default: false }

outputs:
  cache-hit:
    value: ${{ steps.update.outputs.cache-hit }}
  key:
    value: ${{ steps.setup.outputs.key }}

runs:
  using: composite
  steps:

    - id: setup
      shell: bash
      run: |
        : setup use-ruby-tools
        given_key="${{ inputs.key }}"
        installer="gem install"
        [ "${{ inputs.document }}" = false ] && installer+=' --no-document'
        version_key="$( (ruby --version; gem --version; echo -- $installer) | tee /dev/stderr | (md5sum||md5) | awk '{print $1}' )"
        key="${given_key:+$given_key-}${version_key}"
        sed 's/^ *//' << END >> $GITHUB_OUTPUT
            command=$installer
            prefix=$(gem environment gemdir)
            key=$key
        END

    - id: update
      uses: tecolicom/actions-install-and-cache@v1
      with:
        run:   ${{ steps.setup.outputs.command }} ${{ inputs.tools }}
        path:  ${{ steps.setup.outputs.prefix }}
        cache: ${{ inputs.cache }}
        key:   ${{ steps.setup.outputs.key }}
        sudo:  true
