name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:

  initial:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    outputs:
      key: ${{ steps.action.outputs.key }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: sinatra
      - run: gem list | grep -C999 sinatra
      - run: test "${{ steps.action.outputs.cache-hit }}" != true

  cached:
    needs: initial
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: sinatra
      - run: gem list | grep -C999 sinatra
      - run: |
          first_key="${{ needs.initial.outputs.key }}"
          second_key="${{ steps.action.outputs.key }}"
          if [ "$first_key" = "$second_key" ]
          then
              test "${{ steps.action.outputs.cache-hit }}" == true
          else
              error="Cache key does not match ($first_key != $second_key)"
              echo "::warning ::$error"
          fi
